lsi: false
safe: true
source: nj-ramadhan
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
#Build settings
markdown: kramdown
theme: minima
